### ISSUE TITLE
flv only broken

### ISSUE THREAD

**Issue by foliovision** [foliovision/freedom-video-player#122]
Original issue link: [#136 flv only broken](https://github.com/flowplayer/flowplayer/issues/136)

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Nov 29, 2012

http://flowplayer.blacktrash.org/fp5/flv.html gives "undefined: Unsupported video"
Also specifying flash engine explicitly does not help.
See also: http://flowplayer.org/forum/#!/moot/3590

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Nov 29, 2012

Also, e.g. specifying a valid webm source, but trying to force flash engine only goes to html5 engine.
Seems like flv does not play at all - except perhaps via rtmp.
I believe that's a regression.

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Nov 30, 2012

Yes. Regression introduced in 5.2.0 - works in 5.1.1.

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Dec 4, 2012

Ah --- flv requires type="video/flv", not video/flash which is for mp4 or rtmp via flash?

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Dec 4, 2012

But then on the other hand flv files are not recognized via rtmp.
This does not work:

``` html
<script type="text/javascript">
flowplayer.conf = {
  rtmp: "rtmp://stream.blacktrash.org/cfx/st"
};
</script>

<div class="flowplayer">
  <video>
    <source type="video/flash" src="ccc">
  </video>
</div>
```

Only mp4 streams are recognized.

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/1748948?v=4' /> [fa1c0n](https://github.com/fa1c0n) commented on Jan 21, 2013

can anyone fix this?

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Jan 21, 2013

@fa1c0n - this was already fixed in 5.3.0, and is not broken in 5.3.1:
http://flowplayer.blacktrash.org/fp5/flv.html
http://flowplayer.blacktrash.org/fp5/rtmp-flv.html
Closing.
